### ISSUE TITLE
A warning is emitted for scalafmt 1.2.0

### ISSUE THREAD

**Issue by aeons** [lucidsoftware/neo-sbt-scalafmt#48]
```
Warning: Unknown Scalafmt version 1.2.0; using 1.0 interface
```

Shouldn't the check just be whether the version is > 1.0, then use 1.0 interface?

**Comment by joeycozza** [comment]
Technically, that is what is happening, it is just providing a warning because we haven't vetted out scalafmt 1.2 to verify that it hasn't broken binary compatability. Olafurpg explains it a little more in this closed PR. 
https://github.com/lucidsoftware/neo-sbt-scalafmt/pull/36

I can go ahead and add 1.2 to the warning check since it appears to be compatible.

**Comment by rossabaker** [comment]
Was scalafmt-1.2 deemed incompatible after all?  I just upgraded to neo-sbt-scalafmt-1.11 and am still seeing this warning.  I'd be happy to send a PR to add 1.2 to the list.

**Comment by joeycozza** [comment]
shoot. I had every intention of doing this. I am really sorry @aeons  and @rossabaker . I will do it right this second and release 1.12. Sorry about that.

**Comment by joeycozza** [comment]
Okay, that is up now. 1.12 is building now.
